jobs:

  hot-spots_integration-tests:
    name: Hot Spots
    run_when: &RUN_WHEN_DEFAULTS
      any branch matches:
        type: branch
        include_match: ^.*$
    context:
      include:
      - path: cider-ci/contexts/hot-spots.yml
        submodule: ['integration-tests']
      task_defaults:
        priority: 10
        #traits:
        #  g2016: true
        max_trials: 3
        eager_trials: 3
      generate_tasks:
        include_match: ^.*(json).*$
        submodule: [integration-tests]
#      tasks:
#        spec/features/branch-triggers_demo-repo_spec.rb:
#          environment_variables:
#            CIDER_CI_TASK_FILE: spec/features/branch-triggers_demo-repo_spec.rb:35

  integration-tests:
    name: Integration Tests
    run_when: *RUN_WHEN_DEFAULTS
    depends_on:
      hot-spots: {job_key: hot-spots_integration-tests, type: job, states: [passed]}
    context:
      include:
      - path: cider-ci/contexts/integration-tests.yml
        submodule: ['integration-tests']
      task_defaults: {}
      # traits:
      #    g2016: true

  build:
    name: Build the Cider-CI Archive
    run_when: *RUN_WHEN_DEFAULTS
    #depends_on:
    #  integration-tests: {job_key: integration-tests,   type: job, states: [passed]}
    context:
      include:
      - path: cider-ci/contexts/build.yml
        submodule: ['deploy']

  test-container-deploy:
    run_when: *RUN_WHEN_DEFAULTS
    depends_on:
      build: {job_key: build,   type: job, states: [passed]}
    name: Test Deploy to a Container
    context:
      include:
        - path: container-test/cider-ci/context.yml
          submodule: [deploy]
