jobs:

  builder-tests:
    name: Builder Tests
    run_when: &RUN_WHEN_DEFAULTS
      any branch matches:
        type: branch
        include_match: ^.*$
    context:
      include:
      - path: cider-ci/tests.yml
        submodule: ['builder']

  integration-tests:
    name: Cider-CI RSpec Integration Tests
    run_when: *RUN_WHEN_DEFAULTS
    context:
      include:
      - path: cider-ci/contexts/integration-tests.yml
        submodule: ['integration-tests']

  build:
    name: Build the Cider-CI Archive
    # depends_on:
    #   integration-tests: {job_key: integration-tests,   type: job, states: [passed]}
    run_when: *RUN_WHEN_DEFAULTS
    context:
      include:
      - path: cider-ci/contexts/build.yml
        submodule: ['deploy']

  test-container-deploy:
    depends_on:
      integration-tests: {job_key: build,   type: job, states: [passed]}
    name: Test Deploy to a Container
    run_when: *RUN_WHEN_DEFAULTS
    context:
      include:
        - path: container-test/cider-ci/context.yml
          submodule: [deploy]
