job_retention_duration: 100 Years
trial_dispatch_timeout: 30 Minutes

database:
  adapter: "postgresql"
  classname: "org.postgresl.Driver"
  subname: "//localhost:5432/cider-ci_v3_development"
  subprotocol: "postgresql"
  user: cider-ci
  password: secret
  max_pool_size: 3

github_authtoken: NULL

hostname: localhost

secret: secret

basic_auth:
  username: service
  password: secret

session:
  secret: "secret"

git_proxy_enabled: false

messaging:
  connection:
    vhost: cider-ci
    host: 127.0.0.1
    username: cider-ci
    password: secret

server_base_url: http://localhost:8888

services:

  api:

    http:
      host: localhost
      port: 8885
      context: /cider-ci
      sub_context: /api
      ssl: false

    nrepl:
      port: 7885
      bind: "127.0.0.1"
      enabled: true

    database:
      max_pool_size: 3


  builder:

    http:
      host: 127.0.0.1
      port: 8884
      context: /cider-ci
      sub_context: /builder
      ssl: false

    nrepl:
      port: 7884
      bind: "127.0.0.1"
      enabled: true

    database:
      max_pool_size: 3


  dispatcher:

    http:
      host: "0.0.0.0"
      port: 8882
      context: '/cider-ci'
      sub_context: '/dispatcher'
      ssl: false

    nrepl:
      port: 7882
      bind: "127.0.0.1"
      enabled: true

    database:
      max_pool_size: 3

  documentation:

    # this is used in  development/test only; apache serves in production
    http:
      host: localhost
      port: 8887
      context: /cider-ci
      sub_context: /documentation
      ssl: false


  notifier:

    http:
      host: 127.0.0.1
      port: 8887
      context: /cider-ci
      sub_context: /notifier
      ssl: false

    nrepl:
      port: 7887
      bind: "127.0.0.1"
      enabled: true

    database:
      max_pool_size: 3


  repository:

    http:
      host: 127.0.0.1
      port: 8881
      context: /cider-ci
      sub_context: /repositories
      ssl: false

    nrepl:
      port: 7881
      bind: "127.0.0.1"
      enabled: true

    database:
      max_pool_size: 3

    repositories:
      path: "./tmp/repositories"


  storage:

    http:
      host: localhost
      port: 8886
      context: /cider-ci
      sub_context: /storage
      ssl: false

    nrepl:
      port: 7886
      bind: "127.0.0.1"
      enabled: true

    database:
      max_pool_size: 3

    stores:

      - url_path_prefix: "/trial-attachments"
        file_path: "./tmp/storage/trial-attachments"
        db_table: trial_attachments

      - url_path_prefix: "/tree-attachments"
        file_path: "./tmp/storage/tree-attachments"
        db_table: tree_attachments


  ui:

    http:
      host: localhost
      port: 8880
      context: /cider-ci
      sub_context: /ui
      ssl: false


# configuration for the reverse proxy for dev and test, not used in production
reverse_proxy:

  http:
    host: localhost
    port: 8888
    ssl: false

  nrepl:
    port: 7888
    bind: "127.0.0.1"
    enabled: true


constants:
  STATES:
    JOB: [failed, aborted, aborting, pending, executing, passed]
    TASK: [failed, aborted, aborting, pending, executing, passed]
    TRIAL: [failed, aborted, aborting, pending, dispatching, executing, passed]
    SCRIPT: [failed, aborted, pending, executing, skipped, passed, waiting]
    FINISHED: [failed, aborted, passed, skipped]
